name: channels-updater
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  fetch_m3u8_job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install firefox
          unzip firefox-profile.zip

      - name: Run Python Script
        run: |
          curl -o channels-scraper.py "${{ secrets.DADDYLIVE_CHANNELS_URL }}"
          python channels-scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add daddylive-channels.m3u8 daddylive-channels-data.json sitecustomize.py
          git diff --staged --quiet || git commit -m "refactor: update channels"
          git push --force
        
